//Question 01;
//Question 02;
var personalMessage = "hello rimsha";
//Question 03;
var myName = "Rimsha";
myName = myName.toLocaleLowerCase();
console.log(myName);
var father_name = "muhammad arshad";
father_name = father_name.toLocaleUpperCase();
console.log(father_name);
var FavouriteCity = "karachi";
FavouriteCity = FavouriteCity.charAt(0).toUpperCase() + FavouriteCity.slice(1).toLocaleLowerCase();
console.log(FavouriteCity);
var school = "spgs";
school = school.charAt(0).toUpperCase() + school.charAt(1).toUpperCase() + school.slice(2).toLowerCase();
console.log(school);
